JASPER-126: Create network components
bcgov/jasper pull request #33
Opened 2024-10-12 00:12 UTC by ronaldo-macapobre

# Pull Request for JIRA Ticket: JIRA-126

## Issue ticket number and link  
https://jag.gov.bc.ca/jira/browse/JASPER-126

## Description

- Simplify ingress/egress rules for Security Group
- Set up traffic routing between ECS and Lambda Security Groups.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Tested by creating 2 EC2 instances and ping each other's private ip address.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2024-10-16 15:56 UTC, WadeBarnes requested changes
I'd recommend adding some IP restrictions on the ingress rules, especially when it comes to port 22.

2024-10-16 15:57 UTC, TimaQT approved these changes

2024-10-16 19:53 UTC, WadeBarnes approved these changes
I'll defer to @amlanc1 for final review and approval

2024-10-17 15:29 UTC, amlanc1 approved these changes
lgtm

2024-10-17 15:32 UTC, merged